# Generated by Django 4.2.14 on 2024-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.IntegerField(choices=[(0, 17), (1, 18), (2, 19), (3, 20), (4, 21), (5, 22)], default=0)),
            ],
        ),
    ]
