# Generated by Django 5.0.7 on 2024-07-24 14:25

import datetime
import django.core.validators
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[reservations.models.Reservation.validate_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 7, 24))]),
        ),
    ]
