# Generated by Django 4.2.14 on 2024-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
