# Generated by Django 5.0.7 on 2024-07-24 15:30

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[reservations.models.Reservation.validate_date]),
        ),
    ]
