# Generated by Django 4.2.14 on 2024-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_table_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.PositiveIntegerField(choices=[(0, '17:00-17:45'), (1, '18:00-18:45'), (2, '19:00-19:45'), (3, '20:00-20:45'), (4, '21:00-21:45'), (5, '22:00-22:45')], default='17:00'),
        ),
    ]
