# Generated by Django 4.2.14 on 2024-07-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slot',
        ),
    ]
